# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reconGUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_faceRecon(object):
    def setupUi(self, faceRecon):
        faceRecon.setObjectName("faceRecon")
        faceRecon.resize(864, 600)
        font = QtGui.QFont()
        font.setKerning(True)
        faceRecon.setFont(font)
        faceRecon.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../pyqt5/facrec.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        faceRecon.setWindowIcon(icon)
        faceRecon.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(faceRecon)
        self.centralwidget.setObjectName("centralwidget")
        self.getVidSub = QtWidgets.QPushButton(self.centralwidget)
        self.getVidSub.setGeometry(QtCore.QRect(30, 120, 89, 25))
        self.getVidSub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.getVidSub.setObjectName("getVidSub")
        self.getVidlabel = QtWidgets.QLabel(self.centralwidget)
        self.getVidlabel.setGeometry(QtCore.QRect(30, 30, 231, 17))
        self.getVidlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.getVidlabel.setObjectName("getVidlabel")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(30, 170, 181, 71))
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start.setToolTip("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("webcam.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon1)
        self.start.setIconSize(QtCore.QSize(44, 49))
        self.start.setObjectName("start")
        self.getVid = QtWidgets.QLineEdit(self.centralwidget)
        self.getVid.setGeometry(QtCore.QRect(30, 60, 231, 51))
        self.getVid.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.getVid.setStatusTip("")
        self.getVid.setObjectName("getVid")
        self.screen = QtWidgets.QGraphicsView(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(290, 10, 491, 421))
        self.screen.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.screen.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.screen.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.screen.setObjectName("screen")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 310, 160, 16))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.horizontalSlider.setMinimum(5)
        self.horizontalSlider.setMaximum(25)
        self.horizontalSlider.setSliderPosition(15)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(True)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.QsliderLabel = QtWidgets.QLabel(self.centralwidget)
        self.QsliderLabel.setGeometry(QtCore.QRect(30, 270, 171, 17))
        self.QsliderLabel.setObjectName("QsliderLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 296, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.personLabel = QtWidgets.QLabel(self.centralwidget)
        self.personLabel.setGeometry(QtCore.QRect(30, 340, 221, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 141, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        self.personLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.personLabel.setFont(font)
        self.personLabel.setObjectName("personLabel")
        self.person_name = QtWidgets.QListWidget(self.centralwidget)
        self.person_name.setGeometry(QtCore.QRect(30, 380, 221, 101))
        self.person_name.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.person_name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.person_name.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.person_name.setAutoScroll(True)
        self.person_name.setViewMode(QtWidgets.QListView.ListMode)
        self.person_name.setModelColumn(0)
        self.person_name.setUniformItemSizes(False)
        self.person_name.setSelectionRectVisible(True)
        self.person_name.setObjectName("person_name")
        faceRecon.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(faceRecon)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 864, 22))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        faceRecon.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(faceRecon)
        self.statusbar.setObjectName("statusbar")
        faceRecon.setStatusBar(self.statusbar)
        self.block_signal = QtWidgets.QAction(faceRecon)
        self.block_signal.setObjectName("block_signal")
        self.actionrarza = QtWidgets.QAction(faceRecon)
        self.actionrarza.setObjectName("actionrarza")
        self.menumenu.addAction(self.block_signal)
        self.menubar.addAction(self.menumenu.menuAction())

        self.retranslateUi(faceRecon)
        QtCore.QMetaObject.connectSlotsByName(faceRecon)

    def retranslateUi(self, faceRecon):
        _translate = QtCore.QCoreApplication.translate
        faceRecon.setWindowTitle(_translate("faceRecon", "reconnaissance facial"))
        self.getVidSub.setText(_translate("faceRecon", "soumettre"))
        self.getVidSub.setShortcut(_translate("faceRecon", "Return"))
        self.getVidlabel.setText(_translate("faceRecon", "déposez une vidéo ici (.mp4)"))
        self.start.setStatusTip(_translate("faceRecon", "cliquez ici si vous voulez utiliser le webcam (ctrl+w)"))
        self.start.setText(_translate("faceRecon", "utiliser webcam"))
        self.start.setShortcut(_translate("faceRecon", "Ctrl+W"))
        self.screen.setStatusTip(_translate("faceRecon", "votre video va etre afficher dans cette écran "))
        self.horizontalSlider.setStatusTip(_translate("faceRecon", "controller la vitesse du traitement du video"))
        self.QsliderLabel.setStatusTip(_translate("faceRecon", "controller la vitesse du traitement du video"))
        self.QsliderLabel.setText(_translate("faceRecon", "vitesse de lecture"))
        self.label.setText(_translate("faceRecon", "x2"))
        self.personLabel.setText(_translate("faceRecon", "nom                 précision"))
        self.person_name.setStatusTip(_translate("faceRecon", "liste des visages réconnue"))
        self.menumenu.setTitle(_translate("faceRecon", "menu"))
        self.block_signal.setText(_translate("faceRecon", "bloquer l\'écran"))
        self.block_signal.setStatusTip(_translate("faceRecon", "bloquer tous les signaux vennant du thread"))
        self.block_signal.setShortcut(_translate("faceRecon", "Ctrl+B"))
        self.actionrarza.setText(_translate("faceRecon", "rarza"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    faceRecon = QtWidgets.QMainWindow()
    ui = Ui_faceRecon()
    ui.setupUi(faceRecon)
    faceRecon.show()
    sys.exit(app.exec_())
